version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:12.18

workflows:
  main:
    jobs:
      - publish:
          context: ah-global
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  publish:
    executor: node
    steps:
      - checkout
      - run:
          name: Authenticate NPM
          command: |
            npm set registry https://$NPM_REGISTRY
            echo "//$NPM_REGISTRY/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish
          command: npm publish --access public
